################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Model_for_PIL/Src/Model_for_PIL.c \
C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Model_for_PIL/Src/Model_for_PIL_ca.c \
C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Model_for_PIL/Src/STM32SerialRtiostream-ProfilerTimer.c \
C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Model_for_PIL/Src/STM32SerialRtiostream-Rtiostream.c \
C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Model_for_PIL/Src/coder_assumptions_app.c \
C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Model_for_PIL/Src/coder_assumptions_data_stream.c \
C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Model_for_PIL/Src/coder_assumptions_flt.c \
C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Model_for_PIL/Src/coder_assumptions_hwimpl.c \
C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Model_for_PIL/Src/coder_assumptions_rtiostream.c \
C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Model_for_PIL/Src/rtGetInf.c \
C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Model_for_PIL/Src/rtGetNaN.c \
C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Model_for_PIL/Src/rt_nonfinite.c \
C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Model_for_PIL/Src/rtiostream_utils.c \
C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Model_for_PIL/Src/xil_data_stream.c \
C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Model_for_PIL/Src/xil_interface.c \
C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Model_for_PIL/Src/xil_interface_lib.c \
C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Model_for_PIL/Src/xil_rtiostream.c \
C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Model_for_PIL/Src/xil_services.c \
C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Model_for_PIL/Src/xilcomms_rtiostream.c 

OBJS += \
./MATLAB/Model_for_PIL.o \
./MATLAB/Model_for_PIL_ca.o \
./MATLAB/STM32SerialRtiostream-ProfilerTimer.o \
./MATLAB/STM32SerialRtiostream-Rtiostream.o \
./MATLAB/coder_assumptions_app.o \
./MATLAB/coder_assumptions_data_stream.o \
./MATLAB/coder_assumptions_flt.o \
./MATLAB/coder_assumptions_hwimpl.o \
./MATLAB/coder_assumptions_rtiostream.o \
./MATLAB/rtGetInf.o \
./MATLAB/rtGetNaN.o \
./MATLAB/rt_nonfinite.o \
./MATLAB/rtiostream_utils.o \
./MATLAB/xil_data_stream.o \
./MATLAB/xil_interface.o \
./MATLAB/xil_interface_lib.o \
./MATLAB/xil_rtiostream.o \
./MATLAB/xil_services.o \
./MATLAB/xilcomms_rtiostream.o 

C_DEPS += \
./MATLAB/Model_for_PIL.d \
./MATLAB/Model_for_PIL_ca.d \
./MATLAB/STM32SerialRtiostream-ProfilerTimer.d \
./MATLAB/STM32SerialRtiostream-Rtiostream.d \
./MATLAB/coder_assumptions_app.d \
./MATLAB/coder_assumptions_data_stream.d \
./MATLAB/coder_assumptions_flt.d \
./MATLAB/coder_assumptions_hwimpl.d \
./MATLAB/coder_assumptions_rtiostream.d \
./MATLAB/rtGetInf.d \
./MATLAB/rtGetNaN.d \
./MATLAB/rt_nonfinite.d \
./MATLAB/rtiostream_utils.d \
./MATLAB/xil_data_stream.d \
./MATLAB/xil_interface.d \
./MATLAB/xil_interface_lib.d \
./MATLAB/xil_rtiostream.d \
./MATLAB/xil_services.d \
./MATLAB/xilcomms_rtiostream.d 


# Each subdirectory must supply rules for building sources it contributes
MATLAB/Model_for_PIL.o: C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Model_for_PIL/Src/Model_for_PIL.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DARM_MATH_CM4 '-DMemUnit_T=uint8_T' '-DMEM_UNIT_BYTES=1' '-DRTIOSTREAM_TX_BUFFER_BYTE_SIZE=128' '-DRTIOSTREAM_RX_BUFFER_BYTE_SIZE=128' '-DCODER_ASSUMPTIONS_ENABLED=1' -DCA_CHECK_FLOATING_POINT_ENABLED -DCA_CHECK_LONG_LONG_ENABLED -DCA_CHECK_DAZ_ENABLED -DSTM32L433xx -c -I../../Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../Drivers/CMSIS/Include -I../../Model_for_PIL/Inc -I../../../../../../../../../MATLAB/STM32-MAT/STM32/pil/stm32SerialRtiostream -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/CoderAssumpTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/XILTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/ert" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src/ext_mode/common" -I"../../../../../../../../../Program Files/MATLAB/R2019a/simulink/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src/utils" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/rtw/targets/pil/c" -I../../../slprj/stm32/Model_for_PIL -I../../../slprj/stm32/Model_for_PIL/coderassumptions -I../../../slprj/stm32/Model_for_PIL/pil -I../../../slprj/stm32/_sharedutils -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"MATLAB/Model_for_PIL.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
MATLAB/Model_for_PIL_ca.o: C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Model_for_PIL/Src/Model_for_PIL_ca.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DARM_MATH_CM4 '-DMemUnit_T=uint8_T' '-DMEM_UNIT_BYTES=1' '-DRTIOSTREAM_TX_BUFFER_BYTE_SIZE=128' '-DRTIOSTREAM_RX_BUFFER_BYTE_SIZE=128' '-DCODER_ASSUMPTIONS_ENABLED=1' -DCA_CHECK_FLOATING_POINT_ENABLED -DCA_CHECK_LONG_LONG_ENABLED -DCA_CHECK_DAZ_ENABLED -DSTM32L433xx -c -I../../Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../Drivers/CMSIS/Include -I../../Model_for_PIL/Inc -I../../../../../../../../../MATLAB/STM32-MAT/STM32/pil/stm32SerialRtiostream -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/CoderAssumpTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/XILTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/ert" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src/ext_mode/common" -I"../../../../../../../../../Program Files/MATLAB/R2019a/simulink/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src/utils" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/rtw/targets/pil/c" -I../../../slprj/stm32/Model_for_PIL -I../../../slprj/stm32/Model_for_PIL/coderassumptions -I../../../slprj/stm32/Model_for_PIL/pil -I../../../slprj/stm32/_sharedutils -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"MATLAB/Model_for_PIL_ca.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
MATLAB/STM32SerialRtiostream-ProfilerTimer.o: C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Model_for_PIL/Src/STM32SerialRtiostream-ProfilerTimer.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DARM_MATH_CM4 '-DMemUnit_T=uint8_T' '-DMEM_UNIT_BYTES=1' '-DRTIOSTREAM_TX_BUFFER_BYTE_SIZE=128' '-DRTIOSTREAM_RX_BUFFER_BYTE_SIZE=128' '-DCODER_ASSUMPTIONS_ENABLED=1' -DCA_CHECK_FLOATING_POINT_ENABLED -DCA_CHECK_LONG_LONG_ENABLED -DCA_CHECK_DAZ_ENABLED -DSTM32L433xx -c -I../../Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../Drivers/CMSIS/Include -I../../Model_for_PIL/Inc -I../../../../../../../../../MATLAB/STM32-MAT/STM32/pil/stm32SerialRtiostream -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/CoderAssumpTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/XILTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/ert" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src/ext_mode/common" -I"../../../../../../../../../Program Files/MATLAB/R2019a/simulink/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src/utils" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/rtw/targets/pil/c" -I../../../slprj/stm32/Model_for_PIL -I../../../slprj/stm32/Model_for_PIL/coderassumptions -I../../../slprj/stm32/Model_for_PIL/pil -I../../../slprj/stm32/_sharedutils -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"MATLAB/STM32SerialRtiostream-ProfilerTimer.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
MATLAB/STM32SerialRtiostream-Rtiostream.o: C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Model_for_PIL/Src/STM32SerialRtiostream-Rtiostream.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DARM_MATH_CM4 '-DMemUnit_T=uint8_T' '-DMEM_UNIT_BYTES=1' '-DRTIOSTREAM_TX_BUFFER_BYTE_SIZE=128' '-DRTIOSTREAM_RX_BUFFER_BYTE_SIZE=128' '-DCODER_ASSUMPTIONS_ENABLED=1' -DCA_CHECK_FLOATING_POINT_ENABLED -DCA_CHECK_LONG_LONG_ENABLED -DCA_CHECK_DAZ_ENABLED -DSTM32L433xx -c -I../../Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../Drivers/CMSIS/Include -I../../Model_for_PIL/Inc -I../../../../../../../../../MATLAB/STM32-MAT/STM32/pil/stm32SerialRtiostream -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/CoderAssumpTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/XILTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/ert" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src/ext_mode/common" -I"../../../../../../../../../Program Files/MATLAB/R2019a/simulink/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src/utils" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/rtw/targets/pil/c" -I../../../slprj/stm32/Model_for_PIL -I../../../slprj/stm32/Model_for_PIL/coderassumptions -I../../../slprj/stm32/Model_for_PIL/pil -I../../../slprj/stm32/_sharedutils -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"MATLAB/STM32SerialRtiostream-Rtiostream.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
MATLAB/coder_assumptions_app.o: C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Model_for_PIL/Src/coder_assumptions_app.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DARM_MATH_CM4 '-DMemUnit_T=uint8_T' '-DMEM_UNIT_BYTES=1' '-DRTIOSTREAM_TX_BUFFER_BYTE_SIZE=128' '-DRTIOSTREAM_RX_BUFFER_BYTE_SIZE=128' '-DCODER_ASSUMPTIONS_ENABLED=1' -DCA_CHECK_FLOATING_POINT_ENABLED -DCA_CHECK_LONG_LONG_ENABLED -DCA_CHECK_DAZ_ENABLED -DSTM32L433xx -c -I../../Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../Drivers/CMSIS/Include -I../../Model_for_PIL/Inc -I../../../../../../../../../MATLAB/STM32-MAT/STM32/pil/stm32SerialRtiostream -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/CoderAssumpTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/XILTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/ert" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src/ext_mode/common" -I"../../../../../../../../../Program Files/MATLAB/R2019a/simulink/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src/utils" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/rtw/targets/pil/c" -I../../../slprj/stm32/Model_for_PIL -I../../../slprj/stm32/Model_for_PIL/coderassumptions -I../../../slprj/stm32/Model_for_PIL/pil -I../../../slprj/stm32/_sharedutils -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"MATLAB/coder_assumptions_app.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
MATLAB/coder_assumptions_data_stream.o: C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Model_for_PIL/Src/coder_assumptions_data_stream.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DARM_MATH_CM4 '-DMemUnit_T=uint8_T' '-DMEM_UNIT_BYTES=1' '-DRTIOSTREAM_TX_BUFFER_BYTE_SIZE=128' '-DRTIOSTREAM_RX_BUFFER_BYTE_SIZE=128' '-DCODER_ASSUMPTIONS_ENABLED=1' -DCA_CHECK_FLOATING_POINT_ENABLED -DCA_CHECK_LONG_LONG_ENABLED -DCA_CHECK_DAZ_ENABLED -DSTM32L433xx -c -I../../Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../Drivers/CMSIS/Include -I../../Model_for_PIL/Inc -I../../../../../../../../../MATLAB/STM32-MAT/STM32/pil/stm32SerialRtiostream -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/CoderAssumpTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/XILTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/ert" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src/ext_mode/common" -I"../../../../../../../../../Program Files/MATLAB/R2019a/simulink/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src/utils" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/rtw/targets/pil/c" -I../../../slprj/stm32/Model_for_PIL -I../../../slprj/stm32/Model_for_PIL/coderassumptions -I../../../slprj/stm32/Model_for_PIL/pil -I../../../slprj/stm32/_sharedutils -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"MATLAB/coder_assumptions_data_stream.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
MATLAB/coder_assumptions_flt.o: C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Model_for_PIL/Src/coder_assumptions_flt.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DARM_MATH_CM4 '-DMemUnit_T=uint8_T' '-DMEM_UNIT_BYTES=1' '-DRTIOSTREAM_TX_BUFFER_BYTE_SIZE=128' '-DRTIOSTREAM_RX_BUFFER_BYTE_SIZE=128' '-DCODER_ASSUMPTIONS_ENABLED=1' -DCA_CHECK_FLOATING_POINT_ENABLED -DCA_CHECK_LONG_LONG_ENABLED -DCA_CHECK_DAZ_ENABLED -DSTM32L433xx -c -I../../Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../Drivers/CMSIS/Include -I../../Model_for_PIL/Inc -I../../../../../../../../../MATLAB/STM32-MAT/STM32/pil/stm32SerialRtiostream -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/CoderAssumpTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/XILTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/ert" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src/ext_mode/common" -I"../../../../../../../../../Program Files/MATLAB/R2019a/simulink/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src/utils" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/rtw/targets/pil/c" -I../../../slprj/stm32/Model_for_PIL -I../../../slprj/stm32/Model_for_PIL/coderassumptions -I../../../slprj/stm32/Model_for_PIL/pil -I../../../slprj/stm32/_sharedutils -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"MATLAB/coder_assumptions_flt.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
MATLAB/coder_assumptions_hwimpl.o: C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Model_for_PIL/Src/coder_assumptions_hwimpl.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DARM_MATH_CM4 '-DMemUnit_T=uint8_T' '-DMEM_UNIT_BYTES=1' '-DRTIOSTREAM_TX_BUFFER_BYTE_SIZE=128' '-DRTIOSTREAM_RX_BUFFER_BYTE_SIZE=128' '-DCODER_ASSUMPTIONS_ENABLED=1' -DCA_CHECK_FLOATING_POINT_ENABLED -DCA_CHECK_LONG_LONG_ENABLED -DCA_CHECK_DAZ_ENABLED -DSTM32L433xx -c -I../../Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../Drivers/CMSIS/Include -I../../Model_for_PIL/Inc -I../../../../../../../../../MATLAB/STM32-MAT/STM32/pil/stm32SerialRtiostream -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/CoderAssumpTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/XILTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/ert" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src/ext_mode/common" -I"../../../../../../../../../Program Files/MATLAB/R2019a/simulink/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src/utils" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/rtw/targets/pil/c" -I../../../slprj/stm32/Model_for_PIL -I../../../slprj/stm32/Model_for_PIL/coderassumptions -I../../../slprj/stm32/Model_for_PIL/pil -I../../../slprj/stm32/_sharedutils -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"MATLAB/coder_assumptions_hwimpl.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
MATLAB/coder_assumptions_rtiostream.o: C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Model_for_PIL/Src/coder_assumptions_rtiostream.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DARM_MATH_CM4 '-DMemUnit_T=uint8_T' '-DMEM_UNIT_BYTES=1' '-DRTIOSTREAM_TX_BUFFER_BYTE_SIZE=128' '-DRTIOSTREAM_RX_BUFFER_BYTE_SIZE=128' '-DCODER_ASSUMPTIONS_ENABLED=1' -DCA_CHECK_FLOATING_POINT_ENABLED -DCA_CHECK_LONG_LONG_ENABLED -DCA_CHECK_DAZ_ENABLED -DSTM32L433xx -c -I../../Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../Drivers/CMSIS/Include -I../../Model_for_PIL/Inc -I../../../../../../../../../MATLAB/STM32-MAT/STM32/pil/stm32SerialRtiostream -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/CoderAssumpTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/XILTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/ert" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src/ext_mode/common" -I"../../../../../../../../../Program Files/MATLAB/R2019a/simulink/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src/utils" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/rtw/targets/pil/c" -I../../../slprj/stm32/Model_for_PIL -I../../../slprj/stm32/Model_for_PIL/coderassumptions -I../../../slprj/stm32/Model_for_PIL/pil -I../../../slprj/stm32/_sharedutils -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"MATLAB/coder_assumptions_rtiostream.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
MATLAB/rtGetInf.o: C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Model_for_PIL/Src/rtGetInf.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DARM_MATH_CM4 '-DMemUnit_T=uint8_T' '-DMEM_UNIT_BYTES=1' '-DRTIOSTREAM_TX_BUFFER_BYTE_SIZE=128' '-DRTIOSTREAM_RX_BUFFER_BYTE_SIZE=128' '-DCODER_ASSUMPTIONS_ENABLED=1' -DCA_CHECK_FLOATING_POINT_ENABLED -DCA_CHECK_LONG_LONG_ENABLED -DCA_CHECK_DAZ_ENABLED -DSTM32L433xx -c -I../../Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../Drivers/CMSIS/Include -I../../Model_for_PIL/Inc -I../../../../../../../../../MATLAB/STM32-MAT/STM32/pil/stm32SerialRtiostream -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/CoderAssumpTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/XILTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/ert" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src/ext_mode/common" -I"../../../../../../../../../Program Files/MATLAB/R2019a/simulink/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src/utils" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/rtw/targets/pil/c" -I../../../slprj/stm32/Model_for_PIL -I../../../slprj/stm32/Model_for_PIL/coderassumptions -I../../../slprj/stm32/Model_for_PIL/pil -I../../../slprj/stm32/_sharedutils -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"MATLAB/rtGetInf.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
MATLAB/rtGetNaN.o: C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Model_for_PIL/Src/rtGetNaN.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DARM_MATH_CM4 '-DMemUnit_T=uint8_T' '-DMEM_UNIT_BYTES=1' '-DRTIOSTREAM_TX_BUFFER_BYTE_SIZE=128' '-DRTIOSTREAM_RX_BUFFER_BYTE_SIZE=128' '-DCODER_ASSUMPTIONS_ENABLED=1' -DCA_CHECK_FLOATING_POINT_ENABLED -DCA_CHECK_LONG_LONG_ENABLED -DCA_CHECK_DAZ_ENABLED -DSTM32L433xx -c -I../../Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../Drivers/CMSIS/Include -I../../Model_for_PIL/Inc -I../../../../../../../../../MATLAB/STM32-MAT/STM32/pil/stm32SerialRtiostream -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/CoderAssumpTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/XILTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/ert" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src/ext_mode/common" -I"../../../../../../../../../Program Files/MATLAB/R2019a/simulink/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src/utils" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/rtw/targets/pil/c" -I../../../slprj/stm32/Model_for_PIL -I../../../slprj/stm32/Model_for_PIL/coderassumptions -I../../../slprj/stm32/Model_for_PIL/pil -I../../../slprj/stm32/_sharedutils -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"MATLAB/rtGetNaN.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
MATLAB/rt_nonfinite.o: C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Model_for_PIL/Src/rt_nonfinite.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DARM_MATH_CM4 '-DMemUnit_T=uint8_T' '-DMEM_UNIT_BYTES=1' '-DRTIOSTREAM_TX_BUFFER_BYTE_SIZE=128' '-DRTIOSTREAM_RX_BUFFER_BYTE_SIZE=128' '-DCODER_ASSUMPTIONS_ENABLED=1' -DCA_CHECK_FLOATING_POINT_ENABLED -DCA_CHECK_LONG_LONG_ENABLED -DCA_CHECK_DAZ_ENABLED -DSTM32L433xx -c -I../../Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../Drivers/CMSIS/Include -I../../Model_for_PIL/Inc -I../../../../../../../../../MATLAB/STM32-MAT/STM32/pil/stm32SerialRtiostream -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/CoderAssumpTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/XILTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/ert" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src/ext_mode/common" -I"../../../../../../../../../Program Files/MATLAB/R2019a/simulink/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src/utils" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/rtw/targets/pil/c" -I../../../slprj/stm32/Model_for_PIL -I../../../slprj/stm32/Model_for_PIL/coderassumptions -I../../../slprj/stm32/Model_for_PIL/pil -I../../../slprj/stm32/_sharedutils -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"MATLAB/rt_nonfinite.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
MATLAB/rtiostream_utils.o: C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Model_for_PIL/Src/rtiostream_utils.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DARM_MATH_CM4 '-DMemUnit_T=uint8_T' '-DMEM_UNIT_BYTES=1' '-DRTIOSTREAM_TX_BUFFER_BYTE_SIZE=128' '-DRTIOSTREAM_RX_BUFFER_BYTE_SIZE=128' '-DCODER_ASSUMPTIONS_ENABLED=1' -DCA_CHECK_FLOATING_POINT_ENABLED -DCA_CHECK_LONG_LONG_ENABLED -DCA_CHECK_DAZ_ENABLED -DSTM32L433xx -c -I../../Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../Drivers/CMSIS/Include -I../../Model_for_PIL/Inc -I../../../../../../../../../MATLAB/STM32-MAT/STM32/pil/stm32SerialRtiostream -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/CoderAssumpTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/XILTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/ert" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src/ext_mode/common" -I"../../../../../../../../../Program Files/MATLAB/R2019a/simulink/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src/utils" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/rtw/targets/pil/c" -I../../../slprj/stm32/Model_for_PIL -I../../../slprj/stm32/Model_for_PIL/coderassumptions -I../../../slprj/stm32/Model_for_PIL/pil -I../../../slprj/stm32/_sharedutils -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"MATLAB/rtiostream_utils.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
MATLAB/xil_data_stream.o: C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Model_for_PIL/Src/xil_data_stream.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DARM_MATH_CM4 '-DMemUnit_T=uint8_T' '-DMEM_UNIT_BYTES=1' '-DRTIOSTREAM_TX_BUFFER_BYTE_SIZE=128' '-DRTIOSTREAM_RX_BUFFER_BYTE_SIZE=128' '-DCODER_ASSUMPTIONS_ENABLED=1' -DCA_CHECK_FLOATING_POINT_ENABLED -DCA_CHECK_LONG_LONG_ENABLED -DCA_CHECK_DAZ_ENABLED -DSTM32L433xx -c -I../../Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../Drivers/CMSIS/Include -I../../Model_for_PIL/Inc -I../../../../../../../../../MATLAB/STM32-MAT/STM32/pil/stm32SerialRtiostream -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/CoderAssumpTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/XILTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/ert" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src/ext_mode/common" -I"../../../../../../../../../Program Files/MATLAB/R2019a/simulink/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src/utils" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/rtw/targets/pil/c" -I../../../slprj/stm32/Model_for_PIL -I../../../slprj/stm32/Model_for_PIL/coderassumptions -I../../../slprj/stm32/Model_for_PIL/pil -I../../../slprj/stm32/_sharedutils -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"MATLAB/xil_data_stream.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
MATLAB/xil_interface.o: C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Model_for_PIL/Src/xil_interface.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DARM_MATH_CM4 '-DMemUnit_T=uint8_T' '-DMEM_UNIT_BYTES=1' '-DRTIOSTREAM_TX_BUFFER_BYTE_SIZE=128' '-DRTIOSTREAM_RX_BUFFER_BYTE_SIZE=128' '-DCODER_ASSUMPTIONS_ENABLED=1' -DCA_CHECK_FLOATING_POINT_ENABLED -DCA_CHECK_LONG_LONG_ENABLED -DCA_CHECK_DAZ_ENABLED -DSTM32L433xx -c -I../../Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../Drivers/CMSIS/Include -I../../Model_for_PIL/Inc -I../../../../../../../../../MATLAB/STM32-MAT/STM32/pil/stm32SerialRtiostream -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/CoderAssumpTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/XILTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/ert" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src/ext_mode/common" -I"../../../../../../../../../Program Files/MATLAB/R2019a/simulink/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src/utils" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/rtw/targets/pil/c" -I../../../slprj/stm32/Model_for_PIL -I../../../slprj/stm32/Model_for_PIL/coderassumptions -I../../../slprj/stm32/Model_for_PIL/pil -I../../../slprj/stm32/_sharedutils -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"MATLAB/xil_interface.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
MATLAB/xil_interface_lib.o: C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Model_for_PIL/Src/xil_interface_lib.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DARM_MATH_CM4 '-DMemUnit_T=uint8_T' '-DMEM_UNIT_BYTES=1' '-DRTIOSTREAM_TX_BUFFER_BYTE_SIZE=128' '-DRTIOSTREAM_RX_BUFFER_BYTE_SIZE=128' '-DCODER_ASSUMPTIONS_ENABLED=1' -DCA_CHECK_FLOATING_POINT_ENABLED -DCA_CHECK_LONG_LONG_ENABLED -DCA_CHECK_DAZ_ENABLED -DSTM32L433xx -c -I../../Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../Drivers/CMSIS/Include -I../../Model_for_PIL/Inc -I../../../../../../../../../MATLAB/STM32-MAT/STM32/pil/stm32SerialRtiostream -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/CoderAssumpTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/XILTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/ert" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src/ext_mode/common" -I"../../../../../../../../../Program Files/MATLAB/R2019a/simulink/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src/utils" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/rtw/targets/pil/c" -I../../../slprj/stm32/Model_for_PIL -I../../../slprj/stm32/Model_for_PIL/coderassumptions -I../../../slprj/stm32/Model_for_PIL/pil -I../../../slprj/stm32/_sharedutils -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"MATLAB/xil_interface_lib.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
MATLAB/xil_rtiostream.o: C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Model_for_PIL/Src/xil_rtiostream.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DARM_MATH_CM4 '-DMemUnit_T=uint8_T' '-DMEM_UNIT_BYTES=1' '-DRTIOSTREAM_TX_BUFFER_BYTE_SIZE=128' '-DRTIOSTREAM_RX_BUFFER_BYTE_SIZE=128' '-DCODER_ASSUMPTIONS_ENABLED=1' -DCA_CHECK_FLOATING_POINT_ENABLED -DCA_CHECK_LONG_LONG_ENABLED -DCA_CHECK_DAZ_ENABLED -DSTM32L433xx -c -I../../Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../Drivers/CMSIS/Include -I../../Model_for_PIL/Inc -I../../../../../../../../../MATLAB/STM32-MAT/STM32/pil/stm32SerialRtiostream -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/CoderAssumpTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/XILTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/ert" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src/ext_mode/common" -I"../../../../../../../../../Program Files/MATLAB/R2019a/simulink/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src/utils" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/rtw/targets/pil/c" -I../../../slprj/stm32/Model_for_PIL -I../../../slprj/stm32/Model_for_PIL/coderassumptions -I../../../slprj/stm32/Model_for_PIL/pil -I../../../slprj/stm32/_sharedutils -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"MATLAB/xil_rtiostream.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
MATLAB/xil_services.o: C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Model_for_PIL/Src/xil_services.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DARM_MATH_CM4 '-DMemUnit_T=uint8_T' '-DMEM_UNIT_BYTES=1' '-DRTIOSTREAM_TX_BUFFER_BYTE_SIZE=128' '-DRTIOSTREAM_RX_BUFFER_BYTE_SIZE=128' '-DCODER_ASSUMPTIONS_ENABLED=1' -DCA_CHECK_FLOATING_POINT_ENABLED -DCA_CHECK_LONG_LONG_ENABLED -DCA_CHECK_DAZ_ENABLED -DSTM32L433xx -c -I../../Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../Drivers/CMSIS/Include -I../../Model_for_PIL/Inc -I../../../../../../../../../MATLAB/STM32-MAT/STM32/pil/stm32SerialRtiostream -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/CoderAssumpTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/XILTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/ert" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src/ext_mode/common" -I"../../../../../../../../../Program Files/MATLAB/R2019a/simulink/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src/utils" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/rtw/targets/pil/c" -I../../../slprj/stm32/Model_for_PIL -I../../../slprj/stm32/Model_for_PIL/coderassumptions -I../../../slprj/stm32/Model_for_PIL/pil -I../../../slprj/stm32/_sharedutils -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"MATLAB/xil_services.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
MATLAB/xilcomms_rtiostream.o: C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Model_for_PIL/Src/xilcomms_rtiostream.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DARM_MATH_CM4 '-DMemUnit_T=uint8_T' '-DMEM_UNIT_BYTES=1' '-DRTIOSTREAM_TX_BUFFER_BYTE_SIZE=128' '-DRTIOSTREAM_RX_BUFFER_BYTE_SIZE=128' '-DCODER_ASSUMPTIONS_ENABLED=1' -DCA_CHECK_FLOATING_POINT_ENABLED -DCA_CHECK_LONG_LONG_ENABLED -DCA_CHECK_DAZ_ENABLED -DSTM32L433xx -c -I../../Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../Drivers/CMSIS/Include -I../../Model_for_PIL/Inc -I../../../../../../../../../MATLAB/STM32-MAT/STM32/pil/stm32SerialRtiostream -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/CoderAssumpTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/XILTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/ert" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src/ext_mode/common" -I"../../../../../../../../../Program Files/MATLAB/R2019a/simulink/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src/utils" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/rtw/targets/pil/c" -I../../../slprj/stm32/Model_for_PIL -I../../../slprj/stm32/Model_for_PIL/coderassumptions -I../../../slprj/stm32/Model_for_PIL/pil -I../../../slprj/stm32/_sharedutils -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"MATLAB/xilcomms_rtiostream.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

