################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Src/main.c \
C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Src/stm32l4xx_hal_msp.c \
C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Src/stm32l4xx_hal_timebase_tim.c \
C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Src/stm32l4xx_it.c \
../Application/User/syscalls.c \
../Application/User/sysmem.c 

OBJS += \
./Application/User/main.o \
./Application/User/stm32l4xx_hal_msp.o \
./Application/User/stm32l4xx_hal_timebase_tim.o \
./Application/User/stm32l4xx_it.o \
./Application/User/syscalls.o \
./Application/User/sysmem.o 

C_DEPS += \
./Application/User/main.d \
./Application/User/stm32l4xx_hal_msp.d \
./Application/User/stm32l4xx_hal_timebase_tim.d \
./Application/User/stm32l4xx_it.d \
./Application/User/syscalls.d \
./Application/User/sysmem.d 


# Each subdirectory must supply rules for building sources it contributes
Application/User/main.o: C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Src/main.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DARM_MATH_CM4 '-DMemUnit_T=uint8_T' '-DMEM_UNIT_BYTES=1' '-DRTIOSTREAM_TX_BUFFER_BYTE_SIZE=128' '-DRTIOSTREAM_RX_BUFFER_BYTE_SIZE=128' '-DCODER_ASSUMPTIONS_ENABLED=1' -DCA_CHECK_FLOATING_POINT_ENABLED -DCA_CHECK_LONG_LONG_ENABLED -DCA_CHECK_DAZ_ENABLED -DSTM32L433xx -c -I../../Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../Drivers/CMSIS/Include -I../../Model_for_PIL/Inc -I../../../../../../../../../MATLAB/STM32-MAT/STM32/pil/stm32SerialRtiostream -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/CoderAssumpTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/XILTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/ert" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src/ext_mode/common" -I"../../../../../../../../../Program Files/MATLAB/R2019a/simulink/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src/utils" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/rtw/targets/pil/c" -I../../../slprj/stm32/Model_for_PIL -I../../../slprj/stm32/Model_for_PIL/coderassumptions -I../../../slprj/stm32/Model_for_PIL/pil -I../../../slprj/stm32/_sharedutils -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Application/User/main.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/stm32l4xx_hal_msp.o: C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Src/stm32l4xx_hal_msp.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DARM_MATH_CM4 '-DMemUnit_T=uint8_T' '-DMEM_UNIT_BYTES=1' '-DRTIOSTREAM_TX_BUFFER_BYTE_SIZE=128' '-DRTIOSTREAM_RX_BUFFER_BYTE_SIZE=128' '-DCODER_ASSUMPTIONS_ENABLED=1' -DCA_CHECK_FLOATING_POINT_ENABLED -DCA_CHECK_LONG_LONG_ENABLED -DCA_CHECK_DAZ_ENABLED -DSTM32L433xx -c -I../../Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../Drivers/CMSIS/Include -I../../Model_for_PIL/Inc -I../../../../../../../../../MATLAB/STM32-MAT/STM32/pil/stm32SerialRtiostream -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/CoderAssumpTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/XILTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/ert" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src/ext_mode/common" -I"../../../../../../../../../Program Files/MATLAB/R2019a/simulink/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src/utils" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/rtw/targets/pil/c" -I../../../slprj/stm32/Model_for_PIL -I../../../slprj/stm32/Model_for_PIL/coderassumptions -I../../../slprj/stm32/Model_for_PIL/pil -I../../../slprj/stm32/_sharedutils -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Application/User/stm32l4xx_hal_msp.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/stm32l4xx_hal_timebase_tim.o: C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Src/stm32l4xx_hal_timebase_tim.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DARM_MATH_CM4 '-DMemUnit_T=uint8_T' '-DMEM_UNIT_BYTES=1' '-DRTIOSTREAM_TX_BUFFER_BYTE_SIZE=128' '-DRTIOSTREAM_RX_BUFFER_BYTE_SIZE=128' '-DCODER_ASSUMPTIONS_ENABLED=1' -DCA_CHECK_FLOATING_POINT_ENABLED -DCA_CHECK_LONG_LONG_ENABLED -DCA_CHECK_DAZ_ENABLED -DSTM32L433xx -c -I../../Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../Drivers/CMSIS/Include -I../../Model_for_PIL/Inc -I../../../../../../../../../MATLAB/STM32-MAT/STM32/pil/stm32SerialRtiostream -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/CoderAssumpTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/XILTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/ert" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src/ext_mode/common" -I"../../../../../../../../../Program Files/MATLAB/R2019a/simulink/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src/utils" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/rtw/targets/pil/c" -I../../../slprj/stm32/Model_for_PIL -I../../../slprj/stm32/Model_for_PIL/coderassumptions -I../../../slprj/stm32/Model_for_PIL/pil -I../../../slprj/stm32/_sharedutils -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Application/User/stm32l4xx_hal_timebase_tim.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/stm32l4xx_it.o: C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Src/stm32l4xx_it.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DARM_MATH_CM4 '-DMemUnit_T=uint8_T' '-DMEM_UNIT_BYTES=1' '-DRTIOSTREAM_TX_BUFFER_BYTE_SIZE=128' '-DRTIOSTREAM_RX_BUFFER_BYTE_SIZE=128' '-DCODER_ASSUMPTIONS_ENABLED=1' -DCA_CHECK_FLOATING_POINT_ENABLED -DCA_CHECK_LONG_LONG_ENABLED -DCA_CHECK_DAZ_ENABLED -DSTM32L433xx -c -I../../Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../Drivers/CMSIS/Include -I../../Model_for_PIL/Inc -I../../../../../../../../../MATLAB/STM32-MAT/STM32/pil/stm32SerialRtiostream -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/CoderAssumpTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/XILTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/ert" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src/ext_mode/common" -I"../../../../../../../../../Program Files/MATLAB/R2019a/simulink/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src/utils" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/rtw/targets/pil/c" -I../../../slprj/stm32/Model_for_PIL -I../../../slprj/stm32/Model_for_PIL/coderassumptions -I../../../slprj/stm32/Model_for_PIL/pil -I../../../slprj/stm32/_sharedutils -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Application/User/stm32l4xx_it.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/syscalls.o: ../Application/User/syscalls.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DARM_MATH_CM4 '-DMemUnit_T=uint8_T' '-DMEM_UNIT_BYTES=1' '-DRTIOSTREAM_TX_BUFFER_BYTE_SIZE=128' '-DRTIOSTREAM_RX_BUFFER_BYTE_SIZE=128' '-DCODER_ASSUMPTIONS_ENABLED=1' -DCA_CHECK_FLOATING_POINT_ENABLED -DCA_CHECK_LONG_LONG_ENABLED -DCA_CHECK_DAZ_ENABLED -DSTM32L433xx -c -I../../Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../Drivers/CMSIS/Include -I../../Model_for_PIL/Inc -I../../../../../../../../../MATLAB/STM32-MAT/STM32/pil/stm32SerialRtiostream -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/CoderAssumpTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/XILTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/ert" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src/ext_mode/common" -I"../../../../../../../../../Program Files/MATLAB/R2019a/simulink/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src/utils" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/rtw/targets/pil/c" -I../../../slprj/stm32/Model_for_PIL -I../../../slprj/stm32/Model_for_PIL/coderassumptions -I../../../slprj/stm32/Model_for_PIL/pil -I../../../slprj/stm32/_sharedutils -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Application/User/syscalls.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/sysmem.o: ../Application/User/sysmem.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DARM_MATH_CM4 '-DMemUnit_T=uint8_T' '-DMEM_UNIT_BYTES=1' '-DRTIOSTREAM_TX_BUFFER_BYTE_SIZE=128' '-DRTIOSTREAM_RX_BUFFER_BYTE_SIZE=128' '-DCODER_ASSUMPTIONS_ENABLED=1' -DCA_CHECK_FLOATING_POINT_ENABLED -DCA_CHECK_LONG_LONG_ENABLED -DCA_CHECK_DAZ_ENABLED -DSTM32L433xx -c -I../../Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../Drivers/CMSIS/Include -I../../Model_for_PIL/Inc -I../../../../../../../../../MATLAB/STM32-MAT/STM32/pil/stm32SerialRtiostream -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/CoderAssumpTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/XILTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/ert" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src/ext_mode/common" -I"../../../../../../../../../Program Files/MATLAB/R2019a/simulink/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src/utils" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/rtw/targets/pil/c" -I../../../slprj/stm32/Model_for_PIL -I../../../slprj/stm32/Model_for_PIL/coderassumptions -I../../../slprj/stm32/Model_for_PIL/pil -I../../../slprj/stm32/_sharedutils -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Application/User/sysmem.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

