################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal.c \
C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_cortex.c \
C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_dma.c \
C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_dma_ex.c \
C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_exti.c \
C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_flash.c \
C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_flash_ex.c \
C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_flash_ramfunc.c \
C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_gpio.c \
C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_i2c.c \
C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_i2c_ex.c \
C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_pwr.c \
C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_pwr_ex.c \
C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_rcc.c \
C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_rcc_ex.c \
C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_tim.c \
C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_tim_ex.c \
C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_uart.c \
C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_uart_ex.c 

OBJS += \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal.o \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_cortex.o \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_dma.o \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_dma_ex.o \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_exti.o \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_flash.o \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_flash_ex.o \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_flash_ramfunc.o \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_gpio.o \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_i2c.o \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_i2c_ex.o \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_pwr.o \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_pwr_ex.o \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_rcc.o \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_rcc_ex.o \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_tim.o \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_tim_ex.o \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_uart.o \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_uart_ex.o 

C_DEPS += \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal.d \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_cortex.d \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_dma.d \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_dma_ex.d \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_exti.d \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_flash.d \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_flash_ex.d \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_flash_ramfunc.d \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_gpio.d \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_i2c.d \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_i2c_ex.d \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_pwr.d \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_pwr_ex.d \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_rcc.d \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_rcc_ex.d \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_tim.d \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_tim_ex.d \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_uart.d \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_uart_ex.d 


# Each subdirectory must supply rules for building sources it contributes
Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal.o: C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DARM_MATH_CM4 '-DMemUnit_T=uint8_T' '-DMEM_UNIT_BYTES=1' '-DRTIOSTREAM_TX_BUFFER_BYTE_SIZE=128' '-DRTIOSTREAM_RX_BUFFER_BYTE_SIZE=128' '-DCODER_ASSUMPTIONS_ENABLED=1' -DCA_CHECK_FLOATING_POINT_ENABLED -DCA_CHECK_LONG_LONG_ENABLED -DCA_CHECK_DAZ_ENABLED -DSTM32L433xx -c -I../../Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../Drivers/CMSIS/Include -I../../Model_for_PIL/Inc -I../../../../../../../../../MATLAB/STM32-MAT/STM32/pil/stm32SerialRtiostream -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/CoderAssumpTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/XILTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/ert" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src/ext_mode/common" -I"../../../../../../../../../Program Files/MATLAB/R2019a/simulink/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src/utils" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/rtw/targets/pil/c" -I../../../slprj/stm32/Model_for_PIL -I../../../slprj/stm32/Model_for_PIL/coderassumptions -I../../../slprj/stm32/Model_for_PIL/pil -I../../../slprj/stm32/_sharedutils -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_cortex.o: C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_cortex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DARM_MATH_CM4 '-DMemUnit_T=uint8_T' '-DMEM_UNIT_BYTES=1' '-DRTIOSTREAM_TX_BUFFER_BYTE_SIZE=128' '-DRTIOSTREAM_RX_BUFFER_BYTE_SIZE=128' '-DCODER_ASSUMPTIONS_ENABLED=1' -DCA_CHECK_FLOATING_POINT_ENABLED -DCA_CHECK_LONG_LONG_ENABLED -DCA_CHECK_DAZ_ENABLED -DSTM32L433xx -c -I../../Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../Drivers/CMSIS/Include -I../../Model_for_PIL/Inc -I../../../../../../../../../MATLAB/STM32-MAT/STM32/pil/stm32SerialRtiostream -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/CoderAssumpTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/XILTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/ert" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src/ext_mode/common" -I"../../../../../../../../../Program Files/MATLAB/R2019a/simulink/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src/utils" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/rtw/targets/pil/c" -I../../../slprj/stm32/Model_for_PIL -I../../../slprj/stm32/Model_for_PIL/coderassumptions -I../../../slprj/stm32/Model_for_PIL/pil -I../../../slprj/stm32/_sharedutils -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_cortex.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_dma.o: C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_dma.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DARM_MATH_CM4 '-DMemUnit_T=uint8_T' '-DMEM_UNIT_BYTES=1' '-DRTIOSTREAM_TX_BUFFER_BYTE_SIZE=128' '-DRTIOSTREAM_RX_BUFFER_BYTE_SIZE=128' '-DCODER_ASSUMPTIONS_ENABLED=1' -DCA_CHECK_FLOATING_POINT_ENABLED -DCA_CHECK_LONG_LONG_ENABLED -DCA_CHECK_DAZ_ENABLED -DSTM32L433xx -c -I../../Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../Drivers/CMSIS/Include -I../../Model_for_PIL/Inc -I../../../../../../../../../MATLAB/STM32-MAT/STM32/pil/stm32SerialRtiostream -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/CoderAssumpTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/XILTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/ert" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src/ext_mode/common" -I"../../../../../../../../../Program Files/MATLAB/R2019a/simulink/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src/utils" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/rtw/targets/pil/c" -I../../../slprj/stm32/Model_for_PIL -I../../../slprj/stm32/Model_for_PIL/coderassumptions -I../../../slprj/stm32/Model_for_PIL/pil -I../../../slprj/stm32/_sharedutils -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_dma.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_dma_ex.o: C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_dma_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DARM_MATH_CM4 '-DMemUnit_T=uint8_T' '-DMEM_UNIT_BYTES=1' '-DRTIOSTREAM_TX_BUFFER_BYTE_SIZE=128' '-DRTIOSTREAM_RX_BUFFER_BYTE_SIZE=128' '-DCODER_ASSUMPTIONS_ENABLED=1' -DCA_CHECK_FLOATING_POINT_ENABLED -DCA_CHECK_LONG_LONG_ENABLED -DCA_CHECK_DAZ_ENABLED -DSTM32L433xx -c -I../../Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../Drivers/CMSIS/Include -I../../Model_for_PIL/Inc -I../../../../../../../../../MATLAB/STM32-MAT/STM32/pil/stm32SerialRtiostream -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/CoderAssumpTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/XILTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/ert" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src/ext_mode/common" -I"../../../../../../../../../Program Files/MATLAB/R2019a/simulink/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src/utils" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/rtw/targets/pil/c" -I../../../slprj/stm32/Model_for_PIL -I../../../slprj/stm32/Model_for_PIL/coderassumptions -I../../../slprj/stm32/Model_for_PIL/pil -I../../../slprj/stm32/_sharedutils -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_dma_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_exti.o: C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_exti.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DARM_MATH_CM4 '-DMemUnit_T=uint8_T' '-DMEM_UNIT_BYTES=1' '-DRTIOSTREAM_TX_BUFFER_BYTE_SIZE=128' '-DRTIOSTREAM_RX_BUFFER_BYTE_SIZE=128' '-DCODER_ASSUMPTIONS_ENABLED=1' -DCA_CHECK_FLOATING_POINT_ENABLED -DCA_CHECK_LONG_LONG_ENABLED -DCA_CHECK_DAZ_ENABLED -DSTM32L433xx -c -I../../Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../Drivers/CMSIS/Include -I../../Model_for_PIL/Inc -I../../../../../../../../../MATLAB/STM32-MAT/STM32/pil/stm32SerialRtiostream -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/CoderAssumpTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/XILTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/ert" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src/ext_mode/common" -I"../../../../../../../../../Program Files/MATLAB/R2019a/simulink/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src/utils" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/rtw/targets/pil/c" -I../../../slprj/stm32/Model_for_PIL -I../../../slprj/stm32/Model_for_PIL/coderassumptions -I../../../slprj/stm32/Model_for_PIL/pil -I../../../slprj/stm32/_sharedutils -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_exti.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_flash.o: C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_flash.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DARM_MATH_CM4 '-DMemUnit_T=uint8_T' '-DMEM_UNIT_BYTES=1' '-DRTIOSTREAM_TX_BUFFER_BYTE_SIZE=128' '-DRTIOSTREAM_RX_BUFFER_BYTE_SIZE=128' '-DCODER_ASSUMPTIONS_ENABLED=1' -DCA_CHECK_FLOATING_POINT_ENABLED -DCA_CHECK_LONG_LONG_ENABLED -DCA_CHECK_DAZ_ENABLED -DSTM32L433xx -c -I../../Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../Drivers/CMSIS/Include -I../../Model_for_PIL/Inc -I../../../../../../../../../MATLAB/STM32-MAT/STM32/pil/stm32SerialRtiostream -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/CoderAssumpTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/XILTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/ert" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src/ext_mode/common" -I"../../../../../../../../../Program Files/MATLAB/R2019a/simulink/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src/utils" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/rtw/targets/pil/c" -I../../../slprj/stm32/Model_for_PIL -I../../../slprj/stm32/Model_for_PIL/coderassumptions -I../../../slprj/stm32/Model_for_PIL/pil -I../../../slprj/stm32/_sharedutils -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_flash.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_flash_ex.o: C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_flash_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DARM_MATH_CM4 '-DMemUnit_T=uint8_T' '-DMEM_UNIT_BYTES=1' '-DRTIOSTREAM_TX_BUFFER_BYTE_SIZE=128' '-DRTIOSTREAM_RX_BUFFER_BYTE_SIZE=128' '-DCODER_ASSUMPTIONS_ENABLED=1' -DCA_CHECK_FLOATING_POINT_ENABLED -DCA_CHECK_LONG_LONG_ENABLED -DCA_CHECK_DAZ_ENABLED -DSTM32L433xx -c -I../../Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../Drivers/CMSIS/Include -I../../Model_for_PIL/Inc -I../../../../../../../../../MATLAB/STM32-MAT/STM32/pil/stm32SerialRtiostream -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/CoderAssumpTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/XILTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/ert" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src/ext_mode/common" -I"../../../../../../../../../Program Files/MATLAB/R2019a/simulink/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src/utils" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/rtw/targets/pil/c" -I../../../slprj/stm32/Model_for_PIL -I../../../slprj/stm32/Model_for_PIL/coderassumptions -I../../../slprj/stm32/Model_for_PIL/pil -I../../../slprj/stm32/_sharedutils -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_flash_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_flash_ramfunc.o: C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_flash_ramfunc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DARM_MATH_CM4 '-DMemUnit_T=uint8_T' '-DMEM_UNIT_BYTES=1' '-DRTIOSTREAM_TX_BUFFER_BYTE_SIZE=128' '-DRTIOSTREAM_RX_BUFFER_BYTE_SIZE=128' '-DCODER_ASSUMPTIONS_ENABLED=1' -DCA_CHECK_FLOATING_POINT_ENABLED -DCA_CHECK_LONG_LONG_ENABLED -DCA_CHECK_DAZ_ENABLED -DSTM32L433xx -c -I../../Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../Drivers/CMSIS/Include -I../../Model_for_PIL/Inc -I../../../../../../../../../MATLAB/STM32-MAT/STM32/pil/stm32SerialRtiostream -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/CoderAssumpTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/XILTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/ert" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src/ext_mode/common" -I"../../../../../../../../../Program Files/MATLAB/R2019a/simulink/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src/utils" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/rtw/targets/pil/c" -I../../../slprj/stm32/Model_for_PIL -I../../../slprj/stm32/Model_for_PIL/coderassumptions -I../../../slprj/stm32/Model_for_PIL/pil -I../../../slprj/stm32/_sharedutils -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_flash_ramfunc.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_gpio.o: C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_gpio.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DARM_MATH_CM4 '-DMemUnit_T=uint8_T' '-DMEM_UNIT_BYTES=1' '-DRTIOSTREAM_TX_BUFFER_BYTE_SIZE=128' '-DRTIOSTREAM_RX_BUFFER_BYTE_SIZE=128' '-DCODER_ASSUMPTIONS_ENABLED=1' -DCA_CHECK_FLOATING_POINT_ENABLED -DCA_CHECK_LONG_LONG_ENABLED -DCA_CHECK_DAZ_ENABLED -DSTM32L433xx -c -I../../Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../Drivers/CMSIS/Include -I../../Model_for_PIL/Inc -I../../../../../../../../../MATLAB/STM32-MAT/STM32/pil/stm32SerialRtiostream -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/CoderAssumpTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/XILTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/ert" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src/ext_mode/common" -I"../../../../../../../../../Program Files/MATLAB/R2019a/simulink/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src/utils" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/rtw/targets/pil/c" -I../../../slprj/stm32/Model_for_PIL -I../../../slprj/stm32/Model_for_PIL/coderassumptions -I../../../slprj/stm32/Model_for_PIL/pil -I../../../slprj/stm32/_sharedutils -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_gpio.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_i2c.o: C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_i2c.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DARM_MATH_CM4 '-DMemUnit_T=uint8_T' '-DMEM_UNIT_BYTES=1' '-DRTIOSTREAM_TX_BUFFER_BYTE_SIZE=128' '-DRTIOSTREAM_RX_BUFFER_BYTE_SIZE=128' '-DCODER_ASSUMPTIONS_ENABLED=1' -DCA_CHECK_FLOATING_POINT_ENABLED -DCA_CHECK_LONG_LONG_ENABLED -DCA_CHECK_DAZ_ENABLED -DSTM32L433xx -c -I../../Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../Drivers/CMSIS/Include -I../../Model_for_PIL/Inc -I../../../../../../../../../MATLAB/STM32-MAT/STM32/pil/stm32SerialRtiostream -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/CoderAssumpTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/XILTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/ert" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src/ext_mode/common" -I"../../../../../../../../../Program Files/MATLAB/R2019a/simulink/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src/utils" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/rtw/targets/pil/c" -I../../../slprj/stm32/Model_for_PIL -I../../../slprj/stm32/Model_for_PIL/coderassumptions -I../../../slprj/stm32/Model_for_PIL/pil -I../../../slprj/stm32/_sharedutils -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_i2c.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_i2c_ex.o: C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_i2c_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DARM_MATH_CM4 '-DMemUnit_T=uint8_T' '-DMEM_UNIT_BYTES=1' '-DRTIOSTREAM_TX_BUFFER_BYTE_SIZE=128' '-DRTIOSTREAM_RX_BUFFER_BYTE_SIZE=128' '-DCODER_ASSUMPTIONS_ENABLED=1' -DCA_CHECK_FLOATING_POINT_ENABLED -DCA_CHECK_LONG_LONG_ENABLED -DCA_CHECK_DAZ_ENABLED -DSTM32L433xx -c -I../../Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../Drivers/CMSIS/Include -I../../Model_for_PIL/Inc -I../../../../../../../../../MATLAB/STM32-MAT/STM32/pil/stm32SerialRtiostream -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/CoderAssumpTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/XILTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/ert" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src/ext_mode/common" -I"../../../../../../../../../Program Files/MATLAB/R2019a/simulink/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src/utils" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/rtw/targets/pil/c" -I../../../slprj/stm32/Model_for_PIL -I../../../slprj/stm32/Model_for_PIL/coderassumptions -I../../../slprj/stm32/Model_for_PIL/pil -I../../../slprj/stm32/_sharedutils -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_i2c_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_pwr.o: C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_pwr.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DARM_MATH_CM4 '-DMemUnit_T=uint8_T' '-DMEM_UNIT_BYTES=1' '-DRTIOSTREAM_TX_BUFFER_BYTE_SIZE=128' '-DRTIOSTREAM_RX_BUFFER_BYTE_SIZE=128' '-DCODER_ASSUMPTIONS_ENABLED=1' -DCA_CHECK_FLOATING_POINT_ENABLED -DCA_CHECK_LONG_LONG_ENABLED -DCA_CHECK_DAZ_ENABLED -DSTM32L433xx -c -I../../Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../Drivers/CMSIS/Include -I../../Model_for_PIL/Inc -I../../../../../../../../../MATLAB/STM32-MAT/STM32/pil/stm32SerialRtiostream -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/CoderAssumpTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/XILTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/ert" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src/ext_mode/common" -I"../../../../../../../../../Program Files/MATLAB/R2019a/simulink/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src/utils" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/rtw/targets/pil/c" -I../../../slprj/stm32/Model_for_PIL -I../../../slprj/stm32/Model_for_PIL/coderassumptions -I../../../slprj/stm32/Model_for_PIL/pil -I../../../slprj/stm32/_sharedutils -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_pwr.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_pwr_ex.o: C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_pwr_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DARM_MATH_CM4 '-DMemUnit_T=uint8_T' '-DMEM_UNIT_BYTES=1' '-DRTIOSTREAM_TX_BUFFER_BYTE_SIZE=128' '-DRTIOSTREAM_RX_BUFFER_BYTE_SIZE=128' '-DCODER_ASSUMPTIONS_ENABLED=1' -DCA_CHECK_FLOATING_POINT_ENABLED -DCA_CHECK_LONG_LONG_ENABLED -DCA_CHECK_DAZ_ENABLED -DSTM32L433xx -c -I../../Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../Drivers/CMSIS/Include -I../../Model_for_PIL/Inc -I../../../../../../../../../MATLAB/STM32-MAT/STM32/pil/stm32SerialRtiostream -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/CoderAssumpTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/XILTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/ert" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src/ext_mode/common" -I"../../../../../../../../../Program Files/MATLAB/R2019a/simulink/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src/utils" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/rtw/targets/pil/c" -I../../../slprj/stm32/Model_for_PIL -I../../../slprj/stm32/Model_for_PIL/coderassumptions -I../../../slprj/stm32/Model_for_PIL/pil -I../../../slprj/stm32/_sharedutils -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_pwr_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_rcc.o: C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_rcc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DARM_MATH_CM4 '-DMemUnit_T=uint8_T' '-DMEM_UNIT_BYTES=1' '-DRTIOSTREAM_TX_BUFFER_BYTE_SIZE=128' '-DRTIOSTREAM_RX_BUFFER_BYTE_SIZE=128' '-DCODER_ASSUMPTIONS_ENABLED=1' -DCA_CHECK_FLOATING_POINT_ENABLED -DCA_CHECK_LONG_LONG_ENABLED -DCA_CHECK_DAZ_ENABLED -DSTM32L433xx -c -I../../Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../Drivers/CMSIS/Include -I../../Model_for_PIL/Inc -I../../../../../../../../../MATLAB/STM32-MAT/STM32/pil/stm32SerialRtiostream -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/CoderAssumpTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/XILTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/ert" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src/ext_mode/common" -I"../../../../../../../../../Program Files/MATLAB/R2019a/simulink/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src/utils" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/rtw/targets/pil/c" -I../../../slprj/stm32/Model_for_PIL -I../../../slprj/stm32/Model_for_PIL/coderassumptions -I../../../slprj/stm32/Model_for_PIL/pil -I../../../slprj/stm32/_sharedutils -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_rcc.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_rcc_ex.o: C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_rcc_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DARM_MATH_CM4 '-DMemUnit_T=uint8_T' '-DMEM_UNIT_BYTES=1' '-DRTIOSTREAM_TX_BUFFER_BYTE_SIZE=128' '-DRTIOSTREAM_RX_BUFFER_BYTE_SIZE=128' '-DCODER_ASSUMPTIONS_ENABLED=1' -DCA_CHECK_FLOATING_POINT_ENABLED -DCA_CHECK_LONG_LONG_ENABLED -DCA_CHECK_DAZ_ENABLED -DSTM32L433xx -c -I../../Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../Drivers/CMSIS/Include -I../../Model_for_PIL/Inc -I../../../../../../../../../MATLAB/STM32-MAT/STM32/pil/stm32SerialRtiostream -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/CoderAssumpTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/XILTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/ert" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src/ext_mode/common" -I"../../../../../../../../../Program Files/MATLAB/R2019a/simulink/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src/utils" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/rtw/targets/pil/c" -I../../../slprj/stm32/Model_for_PIL -I../../../slprj/stm32/Model_for_PIL/coderassumptions -I../../../slprj/stm32/Model_for_PIL/pil -I../../../slprj/stm32/_sharedutils -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_rcc_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_tim.o: C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_tim.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DARM_MATH_CM4 '-DMemUnit_T=uint8_T' '-DMEM_UNIT_BYTES=1' '-DRTIOSTREAM_TX_BUFFER_BYTE_SIZE=128' '-DRTIOSTREAM_RX_BUFFER_BYTE_SIZE=128' '-DCODER_ASSUMPTIONS_ENABLED=1' -DCA_CHECK_FLOATING_POINT_ENABLED -DCA_CHECK_LONG_LONG_ENABLED -DCA_CHECK_DAZ_ENABLED -DSTM32L433xx -c -I../../Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../Drivers/CMSIS/Include -I../../Model_for_PIL/Inc -I../../../../../../../../../MATLAB/STM32-MAT/STM32/pil/stm32SerialRtiostream -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/CoderAssumpTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/XILTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/ert" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src/ext_mode/common" -I"../../../../../../../../../Program Files/MATLAB/R2019a/simulink/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src/utils" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/rtw/targets/pil/c" -I../../../slprj/stm32/Model_for_PIL -I../../../slprj/stm32/Model_for_PIL/coderassumptions -I../../../slprj/stm32/Model_for_PIL/pil -I../../../slprj/stm32/_sharedutils -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_tim.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_tim_ex.o: C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_tim_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DARM_MATH_CM4 '-DMemUnit_T=uint8_T' '-DMEM_UNIT_BYTES=1' '-DRTIOSTREAM_TX_BUFFER_BYTE_SIZE=128' '-DRTIOSTREAM_RX_BUFFER_BYTE_SIZE=128' '-DCODER_ASSUMPTIONS_ENABLED=1' -DCA_CHECK_FLOATING_POINT_ENABLED -DCA_CHECK_LONG_LONG_ENABLED -DCA_CHECK_DAZ_ENABLED -DSTM32L433xx -c -I../../Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../Drivers/CMSIS/Include -I../../Model_for_PIL/Inc -I../../../../../../../../../MATLAB/STM32-MAT/STM32/pil/stm32SerialRtiostream -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/CoderAssumpTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/XILTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/ert" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src/ext_mode/common" -I"../../../../../../../../../Program Files/MATLAB/R2019a/simulink/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src/utils" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/rtw/targets/pil/c" -I../../../slprj/stm32/Model_for_PIL -I../../../slprj/stm32/Model_for_PIL/coderassumptions -I../../../slprj/stm32/Model_for_PIL/pil -I../../../slprj/stm32/_sharedutils -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_tim_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_uart.o: C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_uart.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DARM_MATH_CM4 '-DMemUnit_T=uint8_T' '-DMEM_UNIT_BYTES=1' '-DRTIOSTREAM_TX_BUFFER_BYTE_SIZE=128' '-DRTIOSTREAM_RX_BUFFER_BYTE_SIZE=128' '-DCODER_ASSUMPTIONS_ENABLED=1' -DCA_CHECK_FLOATING_POINT_ENABLED -DCA_CHECK_LONG_LONG_ENABLED -DCA_CHECK_DAZ_ENABLED -DSTM32L433xx -c -I../../Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../Drivers/CMSIS/Include -I../../Model_for_PIL/Inc -I../../../../../../../../../MATLAB/STM32-MAT/STM32/pil/stm32SerialRtiostream -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/CoderAssumpTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/XILTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/ert" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src/ext_mode/common" -I"../../../../../../../../../Program Files/MATLAB/R2019a/simulink/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src/utils" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/rtw/targets/pil/c" -I../../../slprj/stm32/Model_for_PIL -I../../../slprj/stm32/Model_for_PIL/coderassumptions -I../../../slprj/stm32/Model_for_PIL/pil -I../../../slprj/stm32/_sharedutils -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_uart.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_uart_ex.o: C:/Users/djtn/Documents/GitHub/dynamic-obstacle-avoidance/Code/Model_for_PIL_PIL/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_uart_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DARM_MATH_CM4 '-DMemUnit_T=uint8_T' '-DMEM_UNIT_BYTES=1' '-DRTIOSTREAM_TX_BUFFER_BYTE_SIZE=128' '-DRTIOSTREAM_RX_BUFFER_BYTE_SIZE=128' '-DCODER_ASSUMPTIONS_ENABLED=1' -DCA_CHECK_FLOATING_POINT_ENABLED -DCA_CHECK_LONG_LONG_ENABLED -DCA_CHECK_DAZ_ENABLED -DSTM32L433xx -c -I../../Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../Drivers/CMSIS/Include -I../../Model_for_PIL/Inc -I../../../../../../../../../MATLAB/STM32-MAT/STM32/pil/stm32SerialRtiostream -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/CoderAssumpTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/extern/include/coder/connectivity/XILTgtAppSvc" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/ert" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/rtw/c/src/ext_mode/common" -I"../../../../../../../../../Program Files/MATLAB/R2019a/simulink/include" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/coder/rtiostream/src/utils" -I"../../../../../../../../../Program Files/MATLAB/R2019a/toolbox/rtw/targets/pil/c" -I../../../slprj/stm32/Model_for_PIL -I../../../slprj/stm32/Model_for_PIL/coderassumptions -I../../../slprj/stm32/Model_for_PIL/pil -I../../../slprj/stm32/_sharedutils -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_uart_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

